# Generated by Django 2.2.1 on 2019-08-14 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0003_auto_20190814_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio',
            new_name='portfolio_site',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='picture',
            new_name='profile_pic',
        ),
    ]
